DROP TABLE prefecture;
CREATE TABLE prefecture(id INTEGER PRIMARY KEY, name text);
INSERT INTO prefecture(id,name) VALUES (1,'ÀÃ≥§∆ª');
INSERT INTO prefecture(id,name) VALUES (2,'¿ƒøπ∏©');
INSERT INTO prefecture(id,name) VALUES (3,'¥‰ºÍ∏©');
INSERT INTO prefecture(id,name) VALUES (4,'µ‹æÎ∏©');
INSERT INTO prefecture(id,name) VALUES (5,'Ω©≈ƒ∏©');
INSERT INTO prefecture(id,name) VALUES (6,'ª≥∑¡∏©');
INSERT INTO prefecture(id,name) VALUES (7,' °≈Á∏©');
INSERT INTO prefecture(id,name) VALUES (8,'∞ÒæÎ∏©');
INSERT INTO prefecture(id,name) VALUES (9,'∆ Ã⁄∏©');
INSERT INTO prefecture(id,name) VALUES (10,'∑≤«œ∏©');
INSERT INTO prefecture(id,name) VALUES (11,'∫Î∂Ã∏©');
INSERT INTO prefecture(id,name) VALUES (12,'¿ÈÕ’∏©');
INSERT INTO prefecture(id,name) VALUES (13,'≈Ïµ˛≈‘');
INSERT INTO prefecture(id,name) VALUES (14,'ø¿∆‡¿Ó∏©');
INSERT INTO prefecture(id,name) VALUES (15,'ø∑≥„∏©');
INSERT INTO prefecture(id,name) VALUES (16,'…Ÿª≥∏©');
INSERT INTO prefecture(id,name) VALUES (17,'¿–¿Ó∏©');
INSERT INTO prefecture(id,name) VALUES (18,' °∞Ê∏©');
INSERT INTO prefecture(id,name) VALUES (19,'ª≥Õ¸∏©');
INSERT INTO prefecture(id,name) VALUES (20,'ƒπÃÓ∏©');
INSERT INTO prefecture(id,name) VALUES (21,'¥Ù…Ï∏©');
INSERT INTO prefecture(id,name) VALUES (22,'¿≈≤¨∏©');
INSERT INTO prefecture(id,name) VALUES (23,'∞¶√Œ∏©');
INSERT INTO prefecture(id,name) VALUES (24,'ª∞Ω≈∏©');
INSERT INTO prefecture(id,name) VALUES (25,'º¢≤Ï∏©');
INSERT INTO prefecture(id,name) VALUES (26,'µ˛≈‘…‹');
INSERT INTO prefecture(id,name) VALUES (27,'¬Á∫Â…‹');
INSERT INTO prefecture(id,name) VALUES (28,' º∏À∏©');
INSERT INTO prefecture(id,name) VALUES (29,'∆‡Œ…∏©');
INSERT INTO prefecture(id,name) VALUES (30,'œ¬≤Œª≥∏©');
INSERT INTO prefecture(id,name) VALUES (31,'ƒªºË∏©');
INSERT INTO prefecture(id,name) VALUES (32,'≈Á∫¨∏©');
INSERT INTO prefecture(id,name) VALUES (33,'≤¨ª≥∏©');
INSERT INTO prefecture(id,name) VALUES (34,'π≠≈Á∏©');
INSERT INTO prefecture(id,name) VALUES (35,'ª≥∏˝∏©');
INSERT INTO prefecture(id,name) VALUES (36,'∆¡≈Á∏©');
INSERT INTO prefecture(id,name) VALUES (37,'π·¿Ó∏©');
INSERT INTO prefecture(id,name) VALUES (38,'∞¶…≤∏©');
INSERT INTO prefecture(id,name) VALUES (39,'π‚√Œ∏©');
INSERT INTO prefecture(id,name) VALUES (40,' °≤¨∏©');
INSERT INTO prefecture(id,name) VALUES (41,'∫¥≤Ï∏©');
INSERT INTO prefecture(id,name) VALUES (42,'ƒπ∫Í∏©');
INSERT INTO prefecture(id,name) VALUES (43,'∑ßÀ‹∏©');
INSERT INTO prefecture(id,name) VALUES (44,'¬Á ¨∏©');
INSERT INTO prefecture(id,name) VALUES (45,'µ‹∫Í∏©');
INSERT INTO prefecture(id,name) VALUES (46,'ºØª˘≈Á∏©');
INSERT INTO prefecture(id,name) VALUES (47,'≤≠∆Ï∏©');

